##########################################################
############SimpleMOTD v1.0 by minecraftguy719############
##########################################################

#&0	BLACK
#&1	DARK BLUE
#&2	DARK GREEN
#&3	DARK AQUA
#&4	DARK RED
#&5	DARK PURPLE 
#&6	GOLD
#&7	GRAY
#&8	DARK GRAY
#&9	INDIGO
#&A GREEN
#&B	AQUA
#&C	RED
#&D	PINK
#&E	YELLOW
#&F	WHITE
#&M	STRIKE THROUGH
#&N	UNDERLINED
#&L	BOLD
#&K	RANDOM
#&O	ITALIC

line1: 'SimpleMOTD by minecraftguy719'
line2: 'Thanks for downloading &4<3'