name: SimpleMOTD
version: 1.1
main: simplemotd.minecraftguy719.Main
Author: minecraftguy719
commands:
   simplemotd:
      description: Main Command for SimpleMOTD.
      usage: /<command>
      aliases: [sm]